#!/usr/bin/env bash
# Bash script that displays numbers from 1 to 100.
# Displays FizzBuzz when the number is a multiple of 3 and 5
# Displays Fizz when the number is multiple of 3
# Displays Buzz when the number is a multiple of 5

number=1
while [ $number -lt 101 ];
do
	if [ $(($number % 3)) == 0 ] && [ $(($number % 5 )) == 0 ];
	then 
		echo "Fizz Buzz"
	elif [ $(($number % 3)) == 0 ];
	then
		echo "Fizz"
	elif [ $(($number % 5 )) == 0 ];
	then
		echo "Buzz"
	else
		echo $number
	fi
	let number+=1

done