#!/usr/bin/env bash
#bash script that tells the tale of the file /etc/passwd

while IFS=':' read -ra line; 
do
	echo "The user ${line[0]//_/} is part of the ${line[3]} gang, lives in ${line[5]} and rides ${line[6]}. ${line[2]} place is protected by the passcode ${line[1]}, more info about the user here: ${line[4]}"

done < /etc/passwd
