#!/usr/bin/env bash
# Bash script that displays the visitor IP 
# along with the HTTP status code from the Apache log file.
# OCCURENCE_NUMBER IP HTTP_CODE


awk -F' ' '{ print $1 " " $9 }' apache-access.log | sort | uniq -c | sort -nr
