#!/usr/bin/env bash
# Bash script should check if the file exists and print
# if the file exists: school file exists
# if the file does not exist: school file does not exist

present=0
for file in *;
do
	if [ "$file" == "school" ];
	then
		let present=1
		echo "school file exists"
		if [ -s "$file" ]
		then
			echo "school file is not empty"
		else
			echo "school file is empty"
		fi
		if [ -f "$file" ]
		then
			echo "school is a regular file"
		fi
	fi
done

if [ $present -eq 0 ];
then
	echo "school file does not exist"
fi

